class WritingPrompt
  # from http://scaleitsimple.com/2018/04/05/111-journal-prompts-for-everyday-reflection/
  PROMPTS = [
    "What are some things I am grateful for today?",
    "What are some of my fears and why are they so scary?",
    "Dear childhood friend…",
    "Dear me one year from now…",
    "Relive a favorite childhood memory, what makes this stand out?",
    "Dear teenage me…",
    "I can’t wait for this to happen…",
    "What is something I need to forgive myself for?",
    "What is something I need to forgive someone else for?",
    "How can forgiveness set me free?",
    "What are some things I would love to start doing and why?",
    "What is something that is making me feel down lately? How can I change it?",
    "How can I be more positive during my day?",
    "What is a secret dream or fantasy of mine?",
    "I have never told anyone this before…",
    "What is the biggest lie I have ever told?",
    "Something I am looking forward to doing soon…",
    "What are some things I would love to learn how to do?",
    "Where are some places I would love to travel too?",
    "This is one of my best memories…",
    "I am thankful for these people in my life. What have they taught me?",
    "I am so glad I got to meet…",
    "Here are some things I love about my job…",
    "These are some nice things I have done for others lately…",
    "Here are some nice things others have done for me lately…",
    "Three emotions I am feeling right now and why…",
    "I feel great when I…",
    "My week has been…",
    "Things I am looking forward to doing next month…",
    "These are some of my personal self-care moments…",
    "Happiness to me means…",
    "I am happiest when I am with…",
    "I can’t wait to overcome… How do I plan on getting there?",
    "What are some short-term goals I would love to accomplish?",
    "5 things I want to improve on. How will I do this?",
    "Interpret a dream I had that was very powerful to me…",
    "5 years from now I will be…",
    "These are all the things that make me smile…",
    "What are some of my best traits?",
    "I am happiest when I am doing.",
    "What are some of my triggers?",
    "Brainstorm ideas of ways to better handle my anger…",
    "What are some of my favorite summer activities?",
    "These are my favorite things about fall?",
    "What do I love to do in the winter?",
    "These are the things that excite me most about spring?",
    "What are five things I can start doing tomorrow to better my life?",
    "How can I save more money?",
    "What makes my family awesome?",
    "My favorite things about my hometown…",
    "My ideal day would be…",
    "Some things that inspire me are…",
    "My personal mantra is…",
    "What does love look like to me…",
    "How have I supported others in a positive way lately?",
    "Describe me in a sentence",
    "Describe my life in a sentence…",
    "How has a painful experience in my life transformed into something positive?",
    "Some personal lessons I have learned in life…",
    "The best advice I can give is…",
    "Here are some things I love about my appearance…",
    "What does my dream life look like?",
    "This is what I need to hear today…",
    "These are the most important things in my life…",
    "What is the bravest thing I have ever done?",
    "Here are all the things that make me feel confident…",
    "What are some of my current interests?",
    "If I could change one thing about my life this would be it…",
    "The best part of my day today was…",
    "What does simplifying my life mean to me?",
    "What inspires me to succeed?",
    "Where is my mental happy place?",
    "Who has strongly influenced me in my life?",
    "Ways I can be a better partner/friend…",
    "Why being kinder to myself is important…",
    "What are some things I have done that make me proud?",
    "What is my 5 year plan?",
    "How have I grown in the past year?",
    "What has been my favorite part of this week?",
    "What are some habits I would love to start?",
    "I would love to learn more about…",
    "What are some ways I can treat myself without spending money?",
    "Here are some of my short-term goals?",
    "Three ways I can give back to my community?",
    "My fear holds me back in these ways…",
    "These are the things that give me anxiety…",
    "Are there any things about my personality that I was insecure about but am now ok with?",
    "What are some of my deepest insecurities?",
    "I hold myself back in what ways and why?",
    "What makes me totally unique?",
    "This is my bucket list…",
    "What is my most treasured possession and why?",
    "These are the things that relax me most…",
    "Something I am loving lately is…",
    "Here are some things I can start doing to be more productive…",
    "What are some things I am really good at?",
    "What is the last romantic gesture I initiated?",
    "Here are some ways I can deal with stress better…",
    "What is something that has been making me feel unhappy lately? How can I change my perspective?",
    "What are some challenges in my life lately? How can I personally try to overcome them?",
    "Five ways I can start improving my health…",
    "What are some negative beliefs I have about myself sometimes? How are they untrue?",
    "What are some ways I can truly care for myself when I am sad?",
    "How can I stop sabotaging myself?",
    "I have improved at these five things…",
    "What were some highlights of my day?",
    "What are some books I would like to read this year?"
  ]

  def self.random_prompt
    PROMPTS.sample
  end
  
end